version: '3'
services:
  app:
    build: .
    volumes:
      - .:/isucon
    command: tail -f /dev/null
    ports:
      - 80:8080
  mysql:
    image: mysql:5.7
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - "mysql-webapp-data:/var/lib/mysql"
    environment:
      - "MYSQL_DATABASE=torb"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_USER=isucon"
      - "MYSQL_PASSWORD=isucon"
      - "TZ=Asia/Tokyo"
    ports:
      - "3306:3306"

volumes:
  mysql-webapp-data:
